### ISSUE TITLE
[bug] make complexity/LoC... description visible once issue has been created

### ISSUE THREAD

**Issue by gpoblon** [ryse-rs/.github#7]
### Current behavior

No description appears after the PR has been created

### Expected behavior

A description of each would help to edit

### Steps to reproduce

Nothing special.

### Impact

I2

### Complexity

C1

### Effort

E1

**Comment by ZialeHub** [comment]
I was exactly thinking about it while reading the previous `TO_PROCESS` issues 😅

**Comment by ZialeHub** [comment]
Why add these two ? Don't Bug, Enhance, and Feature cover all aspects ?
```
Basic issue + TEST SCORE HIDDEN 
doc + test + minor + immediate changes only! Self-assigned.
```

```
Basic issue for simple immediate changes. Self-assigned
doc + test + minor + immediate changes only! Self-assigned.
```

**Comment by gpoblon** [comment]
I felt like adding tests or documentation or Readme changes is something we should track but does not fit what we had. Plus for small changes theses issues felt heavy before the rework.

The two basic examples are one and the same, it's just that one is a demo for you to say what you prefer regarding the scoring system display. Try out : create an issue with each basic template you'll understand

**Comment by ZialeHub** [comment]
The basic issue with the scoring system hidden in a accordion seems to be the best option, but we should be able to edit the scoring values once the accordion extended. 👍🏼
